flare:
  fhir:
    server: 'http://localhost:8082/fhir'
    user: ''
    password: ''
    pageCount: 1000
  cache:
    mem:
      sizeMB: 1024
      expire: 'PT48H'
      refresh: 'PT24H'
    disk:
      path: 'cache'
      expire: 'P7D'
      threads: 4
  mapping:
    mappingsFile: 'ontology/codex-term-code-mapping.json'
    conceptTreeFile: 'ontology/codex-code-tree.json'

server:
  port: 8080
