flare:
  fhir:
    server: 'http://localhost:8082/fhir'
    user: ''
    password: ''
    maxConnections: ${FLARE_FHIR_MAX_CONNECTIONS:4}
    pageCount: ${FLARE_FHIR_PAGE_COUNT:1000}
  cache:
    mem:
      sizeMB: ${FLARE_CACHE_MEM_SIZE_MB:1024}
      expire: 'PT48H'
      refresh: 'PT24H'
    disk:
      path: 'cache'
      expire: 'P7D'
      threads: 4
  mapping:
    mappingFile: ${FLARE_MAPPING_MAPPING_FILE:ontology/codex-term-code-mapping.json}
    conceptTreeFile: ${FLARE_MAPPING_CONCEPT_TREE_FILE:ontology/codex-code-tree.json}

server:
  port: 8080

logging:
  level:
    com:
      github:
        benmanes:
          caffeine: 'error'
    de:
      medizininformatikinitiative:
        flare: ${LOG_LEVEL:info}
