name: Build

on:
  push:
    branches:
      - main
      - develop
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - main
      - develop
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Cache Local Maven Repo
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('pom.xml') }}
      - name: Build
        run: mvn -B verify -DskipTests
      - name: Upload Flare Jar
        uses: actions/upload-artifact@v3
        with:
          name: flare-jar
          path: target/flare.jar
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Export to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: flare:latest
          outputs: type=docker,dest=/tmp/flare.tar
      - name: Upload flare Image
        uses: actions/upload-artifact@v3
        with:
          name: flare-image
          path: /tmp/flare.tar

  push-image:
    needs: build
    runs-on: ubuntu-22.04
    if: ${{ ! startsWith(github.head_ref, 'dependabot/')}}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Set up JDK 17 for Maven Build
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Maven Build for Ontology Download
        run: mvn process-resources
      - name: Download Flare Jar
        uses: actions/download-artifact@v3
        with:
          name: flare-jar
          path: target
      - name: Download Flare Image
        uses: actions/download-artifact@v3
        with:
          name: flare-image
          path: /tmp
      - name: Load Flare Image
        run: docker load --input /tmp/flare.tar
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: docker-meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/medizininformatik-initiative/flare
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
